import { makeStyles, tokens } from "@fluentui/react-components";

export const useDashboardStyles = makeStyles({
    brandHeader: {
        display: "flex",
        alignItems: "center",
        gap: tokens.spacingHorizontalS,
    },
    brandLogo: {
        width: "32px",
        height: "32px",
        objectFit: "contain",
    },
    statHeader: {
        display: "flex",
        alignItems: "center",
        gap: tokens.spacingHorizontalXS,
    },
    statIcon: {
        width: "16px",
        height: "16px",
        flexShrink: 0,
    },
    statIconArtists: {
        color: "var(--dg-accent-artists)",
    },
    statIconAlbums: {
        color: "var(--dg-accent-albums)",
    },
    statIconTracks: {
        color: "var(--dg-accent-tracks)",
    },
    statIconVideos: {
        color: "var(--dg-accent-videos)",
    },
    emptyState: {
        textAlign: "center",
        padding: tokens.spacingVerticalXXL,
        color: tokens.colorNeutralForeground3,
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        gap: tokens.spacingVerticalM,
        backgroundColor: `color-mix(in srgb, ${tokens.colorNeutralBackground1} 60%, transparent)`,
        backdropFilter: "blur(20px)",
        WebkitBackdropFilter: "blur(20px)",
        borderRadius: tokens.borderRadiusMedium,
        border: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke2}`,
        overflow: "hidden",
    },
    emptyStateIcon: {
        width: "64px",
        height: "64px",
        color: tokens.colorNeutralForeground4,
        opacity: 0.6,
    },
    emptyStateTitle: {
        color: tokens.colorNeutralForeground1,
        fontWeight: tokens.fontWeightBold,
        textAlign: "center",
    },
    emptyStateSubtitle: {
        color: tokens.colorNeutralForeground3,
        textAlign: "center",
        maxWidth: "560px",
    },
    tabSection: {
        display: "flex",
        flexDirection: "column",
        gap: tokens.spacingVerticalS,
    },

    // Queue styles
    queueCard: {
        padding: tokens.spacingHorizontalM,
        display: "flex",
        flexDirection: "column",
        gap: tokens.spacingVerticalM,
        backgroundColor: `color-mix(in srgb, ${tokens.colorNeutralBackground1} 60%, transparent)`,
        backdropFilter: "blur(20px)",
        borderRadius: tokens.borderRadiusMedium,
        border: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke2}`,
    },
    downloadList: {
        display: "flex",
        flexDirection: "column",
        backgroundColor: `color-mix(in srgb, ${tokens.colorNeutralBackground1} 60%, transparent)`,
        backdropFilter: "blur(20px)",
        borderRadius: tokens.borderRadiusMedium,
        border: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke2}`,
        overflow: "hidden",
    },
    downloadItem: {
        display: "flex",
        alignItems: "center",
        gap: tokens.spacingHorizontalM,
        padding: tokens.spacingHorizontalM,
        borderBottom: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke2}`,
        cursor: "pointer",
        transitionProperty: "background-color",
        transitionDuration: tokens.durationFaster,
        ":hover": {
            backgroundColor: tokens.colorNeutralBackground1Hover,
        },
        ":last-child": {
            borderBottom: "none",
        },
    },
    downloadSubItem: {
        display: "flex",
        alignItems: "center",
        gap: tokens.spacingHorizontalM,
        padding: `${tokens.spacingHorizontalS} ${tokens.spacingHorizontalM} ${tokens.spacingHorizontalS} ${tokens.spacingHorizontalS}`,
        borderBottom: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke2}`,
        backgroundColor: `color-mix(in srgb, ${tokens.colorNeutralBackground1} 20%, transparent)`,
        cursor: "pointer",
        transitionProperty: "background-color",
        transitionDuration: tokens.durationFaster,
        ":hover": {
            backgroundColor: tokens.colorNeutralBackground1Hover,
        },
        ":last-child": {
            borderBottom: "none",
        },
    },
    downloadTrackLead: {
        display: "flex",
        alignItems: "center",
        gap: tokens.spacingHorizontalXS,
        flexShrink: 0,
    },
    downloadStatusLead: {
        width: "16px",
        minWidth: "16px",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        flexShrink: 0,
    },
    downloadStatusText: {
        fontSize: tokens.fontSizeBase200,
        color: tokens.colorNeutralForeground2,
        whiteSpace: "nowrap",
        textTransform: "lowercase",
    },
    downloadStatusPendingIcon: {
        width: "16px",
        height: "16px",
        color: tokens.colorNeutralForeground3,
        flexShrink: 0,
    },
    downloadStatusCompleteIcon: {
        width: "16px",
        height: "16px",
        color: tokens.colorPaletteGreenForeground1,
        flexShrink: 0,
    },
    downloadStatusErrorIcon: {
        width: "16px",
        height: "16px",
        color: tokens.colorPaletteRedForeground1,
        flexShrink: 0,
    },
    downloadCover: {
        width: "40px",
        height: "40px",
        borderRadius: tokens.borderRadiusSmall,
        objectFit: "cover",
        backgroundColor: tokens.colorNeutralBackground3,
        flexShrink: 0,
    },
    downloadCoverVideo: {
        width: "60px",
        height: "40px",
        borderRadius: tokens.borderRadiusSmall,
        objectFit: "cover",
        backgroundColor: tokens.colorNeutralBackground3,
        flexShrink: 0,
    },
    downloadCoverPlaceholder: {
        width: "40px",
        height: "40px",
        borderRadius: tokens.borderRadiusSmall,
        backgroundColor: tokens.colorNeutralBackground3,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        flexShrink: 0,
        color: tokens.colorNeutralForeground4,
    },
    downloadCoverPlaceholderVideo: {
        width: "60px",
        height: "40px",
        borderRadius: tokens.borderRadiusSmall,
        backgroundColor: tokens.colorNeutralBackground3,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        flexShrink: 0,
        color: tokens.colorNeutralForeground4,
    },
    downloadInfo: {
        flex: 1,
        minWidth: 0,
        display: "flex",
        flexDirection: "column",
        gap: tokens.spacingVerticalXXS,
    },
    downloadHeaderRow: {
        display: "flex",
        flexDirection: "column",
        gap: tokens.spacingVerticalXXS,
        minWidth: 0,
        "@media (min-width: 960px)": {
            flexDirection: "row",
            alignItems: "center",
            gap: tokens.spacingHorizontalM,
        },
    },
    downloadTitleRow: {
        display: "flex",
        alignItems: "center",
        gap: tokens.spacingHorizontalXS,
        minWidth: 0,
    },
    downloadTitle: {
        fontWeight: tokens.fontWeightSemibold,
        fontSize: tokens.fontSizeBase300,
        flex: 1,
        overflow: "hidden",
        textOverflow: "ellipsis",
        whiteSpace: "nowrap",
    },
    downloadSubtleText: {
        color: tokens.colorNeutralForeground2,
    },
    downloadArtist: {
        fontSize: tokens.fontSizeBase200,
        color: tokens.colorNeutralForeground3,
        overflow: "hidden",
        textOverflow: "ellipsis",
        whiteSpace: "nowrap",
        minWidth: 0,
    },
    downloadArtistMetaRow: {
        display: "flex",
        alignItems: "center",
        gap: tokens.spacingHorizontalXS,
        flexWrap: "wrap",
        minWidth: 0,
        "@media (min-width: 960px)": {
            flexWrap: "nowrap",
            minWidth: "auto",
            gap: tokens.spacingHorizontalM,
        },
    },
    downloadBadgeRow: {
        display: "flex",
        alignItems: "center",
        gap: tokens.spacingHorizontalXS,
        flexWrap: "wrap",
        minWidth: 0,
        "@media (min-width: 960px)": {
            flexWrap: "nowrap",
        },
    },
    downloadProgress: {
        display: "flex",
        alignItems: "center",
        gap: tokens.spacingHorizontalS,
    },
    progressBarWrapper: {
        flex: 1,
        minWidth: "60px",
    },
    progressText: {
        fontSize: tokens.fontSizeBase200,
        color: tokens.colorNeutralForeground2,
        whiteSpace: "nowrap",
        minWidth: "40px",
        textAlign: "right",
    },
    downloadMeta: {
        fontSize: tokens.fontSizeBase100,
        color: tokens.colorNeutralForeground3,
        overflow: "hidden",
        textOverflow: "ellipsis",
        whiteSpace: "nowrap",
    },
    downloadActions: {
        display: "flex",
        gap: tokens.spacingHorizontalXS,
        flexShrink: 0,
    },
    downloadStateIndicator: {
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        flexShrink: 0,
    },
    downloadTrackNumber: {
        minWidth: "20px",
        textAlign: "right",
        fontSize: tokens.fontSizeBase200,
        color: tokens.colorNeutralForeground2,
        flexShrink: 0,
    },

    // Activity styles
    activityList: {
        display: "flex",
        flexDirection: "column",
        backgroundColor: `color-mix(in srgb, ${tokens.colorNeutralBackground1} 60%, transparent)`,
        backdropFilter: "blur(20px)",
        borderRadius: tokens.borderRadiusMedium,
        border: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke2}`,
        overflow: "hidden",
    },
    activitySection: {
        display: "flex",
        flexDirection: "column",
        ":not(:first-child)": {
            borderTop: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke2}`,
        },
    },
    activitySectionHeader: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        gap: tokens.spacingHorizontalS,
        padding: `${tokens.spacingVerticalXS} ${tokens.spacingHorizontalM}`,
        backgroundColor: `color-mix(in srgb, ${tokens.colorNeutralBackground3} 68%, transparent)`,
        borderBottom: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke2}`,
    },
    activitySectionItems: {
        display: "flex",
        flexDirection: "column",
    },
    activitySectionLabel: {
        color: tokens.colorNeutralForeground2,
        letterSpacing: "0.04em",
        textTransform: "uppercase",
    },
    activitySectionCount: {
        color: tokens.colorNeutralForeground3,
    },
    activityItem: {
        display: "flex",
        alignItems: "center",
        gap: tokens.spacingHorizontalM,
        padding: `${tokens.spacingVerticalS} ${tokens.spacingHorizontalM}`,
        borderBottom: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke2}`,
        "@media (max-width: 959px)": {
            padding: tokens.spacingHorizontalM,
        },
        ":last-child": {
            borderBottom: "none",
        },
    },
    activityItemDefault: {
        borderLeft: `3px solid ${tokens.colorBrandForeground1}`,
    },
    activityItemUpgrade: {
        borderLeft: `3px solid ${tokens.colorPaletteBlueForeground2}`,
    },
    activityLeading: {
        width: "40px",
        textAlign: "center",
        flexShrink: 0,
    },
    activityLeadingContent: {
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        gap: tokens.spacingHorizontalS,
    },
    activityLeadingContentCompact: {
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
    },
    activityIconOffset: {
        marginLeft: tokens.spacingHorizontalS,
        display: "inline-flex",
    },
    activityContent: {
        flex: 1,
        minWidth: 0,
        display: "flex",
        flexDirection: "column",
        gap: tokens.spacingVerticalXXS,
    },
    activitySummaryRow: {
        display: "flex",
        flexDirection: "column",
        gap: tokens.spacingVerticalXXS,
        minWidth: 0,
        "@media (min-width: 600px) and (orientation: landscape)": {
            flexDirection: "row",
            alignItems: "baseline",
            gap: tokens.spacingHorizontalXS,
        },
        "@media (min-width: 960px)": {
            flexDirection: "row",
            alignItems: "baseline",
            gap: tokens.spacingHorizontalS,
        },
    },
    activityTitleText: {
        minWidth: 0,
        overflow: "hidden",
        textOverflow: "ellipsis",
        whiteSpace: "nowrap",
        flexShrink: 0,
    },
    activityInlineDescription: {
        color: tokens.colorNeutralForeground2,
        minWidth: 0,
        overflow: "hidden",
        textOverflow: "ellipsis",
        whiteSpace: "nowrap",
    },
    activitySecondaryText: {
        color: tokens.colorNeutralForeground2,
        marginTop: tokens.spacingVerticalSNudge,
    },
    activityErrorText: {
        color: tokens.colorPaletteRedForeground1,
        marginTop: tokens.spacingVerticalXXS,
        whiteSpace: "normal",
        overflowWrap: "anywhere",
    },
    activityTimeColumn: {
        width: "80px",
        textAlign: "right",
        flexShrink: 0,
    },
    activityTimeActions: {
        display: "flex",
        alignItems: "center",
        justifyContent: "flex-end",
        gap: tokens.spacingHorizontalS,
    },
    activityTime: {
        fontSize: tokens.fontSizeBase100,
        color: tokens.colorNeutralForeground3,
    },
    statusIconSuccess: {
        color: tokens.colorPaletteGreenForeground1,
        width: "16px",
        height: "16px",
    },
    statusIconError: {
        color: tokens.colorPaletteRedForeground1,
        width: "16px",
        height: "16px",
    },
    statusIconNeutral: {
        color: tokens.colorNeutralForeground3,
        width: "16px",
        height: "16px",
    },
    loadMoreRow: {
        display: "flex",
        justifyContent: "center",
        marginTop: tokens.spacingVerticalM,
    },
});
