import { makeStyles, tokens } from "@fluentui/react-components";

export const useDashboardStyles = makeStyles({
    brandHeader: {
        display: "flex",
        alignItems: "center",
        gap: tokens.spacingHorizontalS,
    },
    brandLogo: {
        width: "32px",
        height: "32px",
        objectFit: "contain",
    },
    statHeader: {
        display: "flex",
        alignItems: "center",
        gap: tokens.spacingHorizontalXS,
    },
    statIcon: {
        width: "16px",
        height: "16px",
        flexShrink: 0,
    },
    statIconArtists: {
        color: "var(--dg-accent-artists)",
    },
    statIconAlbums: {
        color: "var(--dg-accent-albums)",
    },
    statIconTracks: {
        color: "var(--dg-accent-tracks)",
    },
    statIconVideos: {
        color: "var(--dg-accent-videos)",
    },
    emptyState: {
        textAlign: "center",
        padding: tokens.spacingVerticalXXL,
        color: tokens.colorNeutralForeground3,
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        gap: tokens.spacingVerticalM,
        backgroundColor: `color-mix(in srgb, ${tokens.colorNeutralBackground1} 60%, transparent)`,
        backdropFilter: "blur(20px)",
        WebkitBackdropFilter: "blur(20px)",
        borderRadius: tokens.borderRadiusMedium,
        border: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke2}`,
        overflow: "hidden",
    },
    emptyStateIcon: {
        width: "64px",
        height: "64px",
        color: tokens.colorNeutralForeground4,
        opacity: 0.6,
    },
    emptyStateTitle: {
        color: tokens.colorNeutralForeground1,
        fontWeight: tokens.fontWeightBold,
        textAlign: "center",
    },
    emptyStateSubtitle: {
        color: tokens.colorNeutralForeground3,
        textAlign: "center",
        maxWidth: "560px",
    },
    tabSection: {
        display: "flex",
        flexDirection: "column",
        gap: tokens.spacingVerticalS,
    },
    queueColumnsWrapper: {
        display: "flex",
        flexDirection: "column" as const,
        gap: tokens.spacingVerticalS,
        "@media (min-width: 960px)": {
            display: "grid",
            gridTemplateColumns: "1fr 1fr",
            gap: tokens.spacingHorizontalL,
            alignItems: "start",
        },
    },
    queueSection: {
        display: "flex",
        flexDirection: "column",
        gap: tokens.spacingVerticalS,
        minWidth: 0,
    },
    queueSectionHeader: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        gap: tokens.spacingHorizontalM,
        flexWrap: "wrap",
    },
    queueSectionHeading: {
        display: "flex",
        flexDirection: "column",
        gap: tokens.spacingVerticalXXS,
        minWidth: 0,
    },
    queueSectionTitle: {
        color: tokens.colorNeutralForeground2,
        margin: 0,
    },
    queueSectionActions: {
        display: "flex",
        alignItems: "center",
        justifyContent: "flex-end",
        gap: tokens.spacingHorizontalS,
        flexWrap: "wrap",
        minWidth: 0,
    },
    queueSectionSelectionCount: {
        color: tokens.colorNeutralForeground3,
        whiteSpace: "nowrap",
    },
    queueSectionHint: {
        color: tokens.colorNeutralForeground3,
    },
    syncNotice: {
        display: "flex",
        alignItems: "center",
        gap: tokens.spacingHorizontalS,
        padding: tokens.spacingHorizontalM,
        borderRadius: tokens.borderRadiusMedium,
        border: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke2}`,
        backgroundColor: `color-mix(in srgb, ${tokens.colorNeutralBackground3} 70%, transparent)`,
        color: tokens.colorNeutralForeground2,
    },
    syncNoticeError: {
        borderTopColor: tokens.colorPaletteRedBorder2,
        borderRightColor: tokens.colorPaletteRedBorder2,
        borderBottomColor: tokens.colorPaletteRedBorder2,
        borderLeftColor: tokens.colorPaletteRedBorder2,
        backgroundColor: `color-mix(in srgb, ${tokens.colorPaletteRedBackground1} 24%, ${tokens.colorNeutralBackground3})`,
    },
    syncNoticeText: {
        color: tokens.colorNeutralForeground2,
    },

    // Queue styles
    queueCard: {
        padding: `${tokens.spacingVerticalS} ${tokens.spacingHorizontalM}`,
        display: "flex",
        flexDirection: "column",
        gap: tokens.spacingVerticalS,
        backgroundColor: `color-mix(in srgb, ${tokens.colorNeutralBackground1} 60%, transparent)`,
        backdropFilter: "blur(20px)",
        borderRadius: tokens.borderRadiusMedium,
        border: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke2}`,
    },
    downloadList: {
        display: "flex",
        flexDirection: "column",
        backgroundColor: `color-mix(in srgb, ${tokens.colorNeutralBackground1} 60%, transparent)`,
        backdropFilter: "blur(20px)",
        borderRadius: tokens.borderRadiusMedium,
        border: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke2}`,
        overflow: "hidden",
    },
    downloadGroup: {
        display: "flex",
        flexDirection: "column",
        position: "relative",
    },
    downloadItem: {
        display: "flex",
        alignItems: "center",
        gap: tokens.spacingHorizontalM,
        padding: tokens.spacingHorizontalM,
        borderBottom: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke2}`,
        cursor: "pointer",
        transitionProperty: "background-color",
        transitionDuration: tokens.durationFaster,
        ":hover": {
            backgroundColor: tokens.colorNeutralBackground1Hover,
        },
        ":last-child": {
            borderBottom: "none",
        },
    },
    downloadItemReorderable: {
        userSelect: "none",
    },
    downloadItemSelected: {
        backgroundColor: `color-mix(in srgb, ${tokens.colorBrandBackground2} 32%, ${tokens.colorNeutralBackground1})`,
        ":hover": {
            backgroundColor: `color-mix(in srgb, ${tokens.colorBrandBackground2} 44%, ${tokens.colorNeutralBackground1Hover})`,
        },
    },
    downloadItemBusy: {
        opacity: 0.68,
    },
    downloadItemDragging: {
        opacity: 0.58,
    },
    downloadItemDropBefore: {
        boxShadow: `inset 0 2px 0 ${tokens.colorBrandStroke1}`,
    },
    downloadItemDropAfter: {
        boxShadow: `inset 0 -2px 0 ${tokens.colorBrandStroke1}`,
    },
    downloadSubItem: {
        display: "flex",
        alignItems: "center",
        gap: tokens.spacingHorizontalM,
        padding: `${tokens.spacingVerticalXS} ${tokens.spacingHorizontalM} ${tokens.spacingVerticalXS} ${tokens.spacingHorizontalS}`,
        borderBottom: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke2}`,
        backgroundColor: `color-mix(in srgb, ${tokens.colorNeutralBackground1} 20%, transparent)`,
        cursor: "pointer",
        transitionProperty: "background-color",
        transitionDuration: tokens.durationFaster,
        ":hover": {
            backgroundColor: tokens.colorNeutralBackground1Hover,
        },
        ":last-child": {
            borderBottom: "none",
        },
    },
    downloadTrackLead: {
        display: "flex",
        alignItems: "center",
        gap: tokens.spacingHorizontalXS,
        flexShrink: 0,
    },
    downloadSelectionCell: {
        display: "flex",
        alignItems: "center",
        gap: tokens.spacingHorizontalXXS,
        flexShrink: 0,
    },
    downloadDragHandle: {
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        width: "20px",
        minWidth: "20px",
        borderRadius: tokens.borderRadiusSmall,
        color: tokens.colorNeutralForeground3,
        fontSize: tokens.fontSizeBase300,
        lineHeight: tokens.lineHeightBase300,
        letterSpacing: "-0.08em",
        cursor: "grab",
        transitionProperty: "background-color, color, opacity",
        transitionDuration: tokens.durationFaster,
        ":hover": {
            backgroundColor: tokens.colorSubtleBackgroundHover,
            color: tokens.colorNeutralForeground2,
        },
        ":active": {
            cursor: "grabbing",
        },
    },
    downloadDragHandleDragging: {
        opacity: 0.6,
    },
    downloadStatusLead: {
        width: "16px",
        minWidth: "16px",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        flexShrink: 0,
    },
    downloadStatusText: {
        fontSize: tokens.fontSizeBase200,
        color: tokens.colorNeutralForeground2,
        whiteSpace: "nowrap",
        textTransform: "lowercase",
    },
    downloadSubItemStatusText: {
        fontSize: tokens.fontSizeBase100,
        lineHeight: tokens.lineHeightBase100,
        color: tokens.colorNeutralForeground2,
        whiteSpace: "nowrap",
        textTransform: "lowercase",
        overflow: "hidden",
        textOverflow: "ellipsis",
    },
    downloadStatusPendingIcon: {
        width: "16px",
        height: "16px",
        color: tokens.colorNeutralForeground3,
        flexShrink: 0,
    },
    downloadStatusCompleteIcon: {
        width: "16px",
        height: "16px",
        color: tokens.colorPaletteGreenForeground1,
        flexShrink: 0,
    },
    downloadStatusErrorIcon: {
        width: "16px",
        height: "16px",
        color: tokens.colorPaletteRedForeground1,
        flexShrink: 0,
    },
    downloadCover: {
        width: "40px",
        height: "40px",
        borderRadius: tokens.borderRadiusSmall,
        objectFit: "cover",
        backgroundColor: tokens.colorNeutralBackground3,
        flexShrink: 0,
    },
    downloadCoverVideo: {
        width: "60px",
        height: "40px",
        borderRadius: tokens.borderRadiusSmall,
        objectFit: "cover",
        backgroundColor: tokens.colorNeutralBackground3,
        flexShrink: 0,
    },
    downloadCoverPlaceholder: {
        width: "40px",
        height: "40px",
        borderRadius: tokens.borderRadiusSmall,
        backgroundColor: tokens.colorNeutralBackground3,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        flexShrink: 0,
        color: tokens.colorNeutralForeground4,
    },
    downloadCoverPlaceholderVideo: {
        width: "60px",
        height: "40px",
        borderRadius: tokens.borderRadiusSmall,
        backgroundColor: tokens.colorNeutralBackground3,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        flexShrink: 0,
        color: tokens.colorNeutralForeground4,
    },
    downloadInfo: {
        flex: 1,
        minWidth: 0,
        display: "flex",
        flexDirection: "column",
        gap: tokens.spacingVerticalXXS,
    },
    downloadHeaderRow: {
        display: "flex",
        flexDirection: "column",
        gap: tokens.spacingVerticalXXS,
        minWidth: 0,
    },
    downloadHeaderRowInline: {
        "@media (min-width: 700px)": {
            flexDirection: "row",
            alignItems: "center",
            gap: tokens.spacingHorizontalM,
        },
    },
    downloadTitleRow: {
        display: "flex",
        alignItems: "center",
        gap: tokens.spacingHorizontalXS,
        minWidth: 0,
    },
    downloadTitle: {
        fontWeight: tokens.fontWeightSemibold,
        fontSize: tokens.fontSizeBase300,
        flex: 1,
        overflow: "hidden",
        textOverflow: "ellipsis",
        whiteSpace: "nowrap",
    },
    downloadSubtleText: {
        color: tokens.colorNeutralForeground2,
    },
    downloadArtist: {
        fontSize: tokens.fontSizeBase200,
        color: tokens.colorNeutralForeground3,
        overflow: "hidden",
        textOverflow: "ellipsis",
        whiteSpace: "nowrap",
        minWidth: 0,
    },
    downloadArtistMetaRow: {
        display: "flex",
        alignItems: "center",
        gap: tokens.spacingHorizontalXS,
        flexWrap: "wrap",
        minWidth: 0,
    },
    downloadArtistMetaRowInline: {
        "@media (min-width: 700px)": {
            flexWrap: "nowrap",
            gap: tokens.spacingHorizontalM,
        },
    },
    downloadBadgeRow: {
        display: "flex",
        alignItems: "center",
        gap: tokens.spacingHorizontalXS,
        flexWrap: "wrap",
        minWidth: 0,
    },
    downloadBadgeRowInline: {
        "@media (min-width: 700px)": {
            flexWrap: "nowrap",
        },
    },
    downloadProgress: {
        display: "flex",
        alignItems: "center",
        gap: tokens.spacingHorizontalS,
    },
    progressBarWrapper: {
        flex: 1,
        minWidth: "60px",
    },
    progressText: {
        fontSize: tokens.fontSizeBase200,
        color: tokens.colorNeutralForeground2,
        whiteSpace: "nowrap",
        minWidth: "40px",
        textAlign: "right",
    },
    downloadMeta: {
        fontSize: tokens.fontSizeBase100,
        color: tokens.colorNeutralForeground3,
        overflow: "hidden",
        textOverflow: "ellipsis",
        whiteSpace: "nowrap",
    },
    downloadActions: {
        display: "flex",
        gap: tokens.spacingHorizontalXS,
        flexWrap: "wrap",
        justifyContent: "flex-end",
        flexShrink: 0,
    },
    queueHistoryItem: {
        outlineStyle: "none",
    },
    queueHistoryItemClickable: {
        cursor: "pointer",
        ":hover": {
            backgroundColor: tokens.colorNeutralBackground1Hover,
        },
        ":focus-visible": {
            outline: `${tokens.strokeWidthThick} solid ${tokens.colorStrokeFocus2}`,
            outlineOffset: `-${tokens.strokeWidthThin}`,
        },
    },
    queueHistoryItemStatic: {
        cursor: "default",
        ":hover": {
            backgroundColor: tokens.colorNeutralBackground1,
        },
    },
    queueHistoryTrailing: {
        display: "flex",
        alignItems: "center",
        gap: tokens.spacingHorizontalS,
        flexShrink: 0,
        marginLeft: "auto",
    },
    queueHistoryStatus: {
        display: "flex",
        alignItems: "center",
        gap: tokens.spacingHorizontalXS,
        flexShrink: 0,
        justifyContent: "flex-end",
    },
    queueHistoryTime: {
        fontSize: tokens.fontSizeBase200,
        color: tokens.colorNeutralForeground3,
        whiteSpace: "nowrap",
    },
    queueHistoryErrorText: {
        fontSize: tokens.fontSizeBase100,
        color: tokens.colorPaletteRedForeground1,
        whiteSpace: "normal",
        overflowWrap: "anywhere",
    },
    downloadReorderActions: {
        display: "flex",
        alignItems: "center",
        gap: tokens.spacingHorizontalXXS,
        flexShrink: 0,
    },
    reorderDesktopOnly: {
        display: "none",
        "@media (min-width: 640px)": {
            display: "inline-flex",
        },
    },
    reorderMobileOnly: {
        display: "inline-flex",
        "@media (min-width: 640px)": {
            display: "none",
        },
    },
    downloadStateIndicator: {
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        flexShrink: 0,
    },
    downloadTrackNumber: {
        minWidth: "20px",
        textAlign: "right",
        fontSize: tokens.fontSizeBase200,
        color: tokens.colorNeutralForeground2,
        flexShrink: 0,
    },

    // Activity styles
    activityList: {
        display: "flex",
        flexDirection: "column",
        backgroundColor: `color-mix(in srgb, ${tokens.colorNeutralBackground1} 60%, transparent)`,
        backdropFilter: "blur(20px)",
        borderRadius: tokens.borderRadiusMedium,
        border: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke2}`,
        overflow: "hidden",
    },
    activitySection: {
        display: "flex",
        flexDirection: "column",
        ":not(:first-child)": {
            borderTop: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke2}`,
        },
    },
    activitySectionHeader: {
        display: "flex",
        alignItems: "center",
        gap: tokens.spacingHorizontalS,
        padding: `${tokens.spacingVerticalM} ${tokens.spacingHorizontalM} ${tokens.spacingVerticalXS}`,
    },
    activitySectionItems: {
        display: "flex",
        flexDirection: "column",
    },
    activitySectionLabel: {
        color: tokens.colorNeutralForeground2,
        fontSize: tokens.fontSizeBase200,
    },
    activitySectionCount: {
        color: tokens.colorNeutralForeground3,
    },
    activityItem: {
        display: "flex",
        alignItems: "flex-start",
        gap: tokens.spacingHorizontalM,
        padding: `${tokens.spacingVerticalS} ${tokens.spacingHorizontalM}`,
        borderBottom: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke2}`,
        cursor: "default",
        transitionProperty: "background-color",
        transitionDuration: tokens.durationFaster,
        ":hover": {
            backgroundColor: tokens.colorSubtleBackgroundHover,
        },
        ":last-child": {
            borderBottom: "none",
        },
    },
    activityLeading: {
        width: "32px",
        textAlign: "center",
        flexShrink: 0,
        paddingTop: tokens.spacingVerticalSNudge,
    },
    activityLeadingContent: {
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        gap: tokens.spacingHorizontalXS,
    },
    activityLeadingContentCompact: {
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        gap: tokens.spacingHorizontalXS,
    },
    activityIconOffset: {
        display: "inline-flex",
    },
    activityContent: {
        flex: 1,
        minWidth: 0,
        display: "flex",
        flexDirection: "column",
        gap: tokens.spacingVerticalXXS,
    },
    activitySummaryRow: {
        display: "flex",
        alignItems: "flex-start",
        justifyContent: "space-between",
        gap: tokens.spacingHorizontalM,
        minWidth: 0,
        "@media (max-width: 699px)": {
            flexDirection: "column",
            gap: tokens.spacingVerticalXS,
        },
    },
    activityTitleStack: {
        display: "flex",
        flexDirection: "column",
        gap: tokens.spacingVerticalXXS,
        flex: 1,
        minWidth: 0,
        "@media (min-width: 700px)": {
            flexDirection: "row",
            alignItems: "baseline",
            flexWrap: "wrap",
            columnGap: tokens.spacingHorizontalXS,
            rowGap: tokens.spacingVerticalXXS,
        },
    },
    activityTitleText: {
        minWidth: 0,
        overflow: "hidden",
        textOverflow: "ellipsis",
        whiteSpace: "normal",
        overflowWrap: "anywhere",
        "@media (min-width: 700px)": {
            flexShrink: 0,
            maxWidth: "100%",
        },
    },
    activityInlineDescription: {
        color: tokens.colorNeutralForeground2,
        whiteSpace: "normal",
        overflowWrap: "anywhere",
        minWidth: 0,
        "@media (min-width: 700px)": {
            flex: "1 1 16rem",
        },
    },
    activitySecondaryText: {
        color: tokens.colorNeutralForeground2,
        marginTop: tokens.spacingVerticalSNudge,
    },
    activityLoadingRow: {
        display: "flex",
        alignItems: "center",
        gap: tokens.spacingHorizontalS,
        padding: `${tokens.spacingVerticalM} ${tokens.spacingHorizontalM}`,
    },
    activityErrorText: {
        color: tokens.colorPaletteRedForeground1,
        whiteSpace: "normal",
        overflowWrap: "anywhere",
        "@media (min-width: 700px)": {
            flexBasis: "100%",
        },
    },
    activityTimeActions: {
        display: "flex",
        alignItems: "center",
        justifyContent: "flex-end",
        gap: tokens.spacingHorizontalXS,
        flexShrink: 0,
        "@media (max-width: 699px)": {
            justifyContent: "flex-start",
        },
    },
    activityTime: {
        fontSize: tokens.fontSizeBase100,
        color: tokens.colorNeutralForeground3,
        whiteSpace: "nowrap",
    },
    statusIconSuccess: {
        color: tokens.colorPaletteGreenForeground1,
        width: "16px",
        height: "16px",
    },
    statusIconSuccessHistory: {
        color: tokens.colorPaletteGreenForeground1,
        width: "20px",
        height: "20px",
    },
    statusIconError: {
        color: tokens.colorPaletteRedForeground1,
        width: "16px",
        height: "16px",
    },
    statusIconNeutral: {
        color: tokens.colorNeutralForeground3,
        width: "16px",
        height: "16px",
    },
    loadMoreRow: {
        display: "flex",
        justifyContent: "center",
        padding: tokens.spacingVerticalM,
    },
});

