import fs from "fs";
import path from "path";
import { Router } from "express";

import { CONFIG_DIR } from "../services/config/config.js";
import { 
  getMediaCoverContentType, 
  resolveMediaCoverFilePath,
  resolveAlbumArtwork,
  resolveArtistArtwork,
  resolveVideoArtwork,
  isArtworkPreferenceCacheCurrent,
} from "../services/metadata/media-cover-service.js";

const router = Router();
const MEDIA_COVER_ROOT = path.join(CONFIG_DIR, "media-cover");

// Sizes generated by prepareResizedMediaCovers(), largest first. Named by
// target *height* (width follows so aspect ratio is preserved — no 3:2 crop).
// Album/artist UI: 500 + 250. Video: bare cover.jpg is origin; cards use 250 only.
const UI_COVER_HEIGHTS = [500, 250] as const;

function requestedCoverHasProxyHeight(filename: string): boolean {
  return /-\d+\.[a-z0-9]+$/i.test(String(filename || ""));
}

/**
 * Resolve a resized UI proxy (`<coverType>-<height>.jpg`). When the source was
 * already small enough no resized file exists and we fall back to the original.
 */
function resolveUiMediaCoverProxyFilePath(folder: string, filename: string): string | null {
  // Strip optional `-<height>` so cover-250.jpg still maps to cover-500/cover-250.
  const coverType = String(filename || "")
    .replace(/-\d+(?=\.[a-z0-9]+$)/i, "")
    .replace(/\.[a-z0-9]+$/i, "");
  for (const height of UI_COVER_HEIGHTS) {
    const resized = resolveMediaCoverFilePath(folder, `${coverType}-${height}.jpg`);
    if (resized) {
      return resized;
    }
  }
  return resolveMediaCoverFilePath(folder, filename);
}

/**
 * Album/artist: prefer proxy. Video: bare cover.jpg is full-res origin; height
 * suffixes are the aspect-preserving proxies used by grids/cards.
 */
function resolveUiMediaCoverFilePath(
  folder: string,
  filename: string,
  options: { preferOrigin?: boolean } = {},
): string | null {
  if (options.preferOrigin && !requestedCoverHasProxyHeight(filename)) {
    return resolveMediaCoverFilePath(folder, filename)
      || resolveUiMediaCoverProxyFilePath(folder, filename);
  }
  return resolveUiMediaCoverProxyFilePath(folder, filename);
}

function sendMediaCover(res: any, filePath: string): void {
  res.setHeader("Content-Type", getMediaCoverContentType(filePath));
  res.setHeader("Cache-Control", "public, max-age=31536000, immutable");
  fs.createReadStream(filePath).pipe(res);
}

async function resolveArtworkWhenNeeded(options: {
  filePath: string | null;
  cacheCurrent: boolean;
  resolve: () => Promise<unknown>;
  refreshFilePath: () => string | null;
  logLabel: string;
}): Promise<string | null> {
  const needsResolve = !options.filePath || !options.cacheCurrent;
  if (!needsResolve) {
    return options.filePath;
  }

  const resolvePromise = options.resolve().catch((error) => {
    console.warn(`[MediaCover Route] Failed to fetch missing ${options.logLabel} on-the-fly:`, error);
  });

  if (options.filePath) {
    void resolvePromise;
    return options.filePath;
  }

  await resolvePromise;
  return options.refreshFilePath();
}

router.get("/Albums/:albumId/:filename", async (req, res) => {
  const albumId = String(req.params.albumId || "").replace(/[^a-zA-Z0-9._-]/g, "_");
  const filename = String(req.params.filename || "");
  const albumFolder = path.join(MEDIA_COVER_ROOT, "Albums", albumId);
  const refreshFilePath = () => resolveUiMediaCoverFilePath(albumFolder, filename);
  let filePath = refreshFilePath();

  filePath = await resolveArtworkWhenNeeded({
    filePath,
    cacheCurrent: isArtworkPreferenceCacheCurrent(albumId, "Album", "Cover"),
    resolve: () => resolveAlbumArtwork({ albumMbid: albumId }),
    refreshFilePath,
    logLabel: `album cover for ${albumId}`,
  });

  if (!filePath) {
    return res.status(404).end();
  }
  return sendMediaCover(res, filePath);
});

router.get("/Videos/:videoId/:filename", async (req, res) => {
  const videoId = String(req.params.videoId || "").replace(/[^a-zA-Z0-9._-]/g, "_");
  const filename = String(req.params.filename || "");
  const videoFolder = path.join(MEDIA_COVER_ROOT, "Videos", videoId);
  const refreshFilePath = () => resolveUiMediaCoverFilePath(videoFolder, filename, { preferOrigin: true });
  let filePath = refreshFilePath();

  if (!filePath) {
    try {
      await resolveVideoArtwork({ videoId });
      filePath = refreshFilePath();
    } catch (error) {
      console.warn(`[MediaCover Route] Failed to fetch missing video cover on-the-fly for ${videoId}:`, error);
    }
  }

  if (!filePath) {
    return res.status(404).end();
  }
  return sendMediaCover(res, filePath);
});

router.get("/:artistId/:filename", async (req, res) => {
  const artistId = String(req.params.artistId || "").replace(/[^a-zA-Z0-9._-]/g, "_");
  const filename = String(req.params.filename || "");
  const requestedCoverType = filename.replace(/-\d+(?=\.[a-z0-9]+$)/i, "").replace(/\.[a-z0-9]+$/i, "") || "Poster";
  const artistFolder = path.join(MEDIA_COVER_ROOT, artistId);
  const refreshFilePath = () => resolveUiMediaCoverFilePath(artistFolder, filename);
  let filePath = refreshFilePath();

  filePath = await resolveArtworkWhenNeeded({
    filePath,
    cacheCurrent: isArtworkPreferenceCacheCurrent(artistId, "Artist", requestedCoverType),
    resolve: () => resolveArtistArtwork({ artistMbid: artistId, preferredCoverTypes: requestedCoverType }),
    refreshFilePath,
    logLabel: `artist cover for ${artistId}`,
  });

  if (!filePath) {
    return res.status(404).end();
  }
  return sendMediaCover(res, filePath);
});

export default router;
