import fs from "fs";
import path from "path";
import { Router } from "express";

import { CONFIG_DIR } from "../services/config/config.js";
import {
  normalizeMediaCoverEntityId,
} from "../services/metadata/media-cover-service.js";

const router = Router();
const MEDIA_COVER_ROOT = path.resolve(CONFIG_DIR, "media-cover");

// Sizes generated by prepareResizedMediaCovers(), largest first. Named by
// target *height* (width follows so aspect ratio is preserved — no 3:2 crop).
// Album/artist UI: 500 + 250. Video: bare cover.jpg is origin; cards use 250 only.
const UI_COVER_HEIGHTS = [500, 250] as const;
const IMAGE_EXTENSIONS = [".jpg", ".jpeg", ".png", ".webp", ".gif"] as const;

function mediaCoverFolder(...segments: string[]): string | null {
  const folder = path.resolve(MEDIA_COVER_ROOT, ...segments);
  return folder === MEDIA_COVER_ROOT || folder.startsWith(`${MEDIA_COVER_ROOT}${path.sep}`)
    ? folder
    : null;
}

function requestedCoverHasProxyHeight(filename: string): boolean {
  return /-\d+\.[a-z0-9]+$/i.test(String(filename || ""));
}

function existingFile(filePath: string): string | null {
  try {
    const stats = fs.statSync(filePath);
    return stats.isFile() && stats.size > 0 ? filePath : null;
  } catch {
    return null;
  }
}

function orderedExtensions(preferredExtension: string): string[] {
  const normalized = preferredExtension.toLowerCase();
  return [
    ...(IMAGE_EXTENSIONS.includes(normalized as typeof IMAGE_EXTENSIONS[number]) ? [normalized] : []),
    ...IMAGE_EXTENSIONS.filter((extension) => extension !== normalized),
  ];
}

function resolveStoredVariant(
  folder: string,
  coverType: string,
  height: number | null,
  preferredExtension: string,
): string | null {
  const suffix = height == null ? "" : `-${height}`;
  for (const extension of orderedExtensions(preferredExtension)) {
    const found = existingFile(path.join(folder, `${coverType}${suffix}${extension}`));
    if (found) {
      return found;
    }
  }
  return null;
}

/**
 * Honor an explicitly requested derivative, then prefer a larger cached
 * derivative, the origin, and finally a smaller derivative. This avoids both
 * serving full video origins to card requests and upscaling a thumbnail for a
 * detail request when the full source is available.
 */
function resolveUiMediaCoverProxyFilePath(folder: string, filename: string): string | null {
  const match = path.basename(String(filename || "")).match(/^(.+?)(?:-(\d+))?(\.[a-z0-9]+)$/i);
  if (!match) {
    return null;
  }

  const [, coverType, requestedHeightText, preferredExtension] = match;
  const requestedHeight = requestedHeightText ? Number.parseInt(requestedHeightText, 10) : null;
  if (requestedHeight == null) {
    for (const height of UI_COVER_HEIGHTS) {
      const resized = resolveStoredVariant(folder, coverType, height, preferredExtension);
      if (resized) return resized;
    }
    return resolveStoredVariant(folder, coverType, null, preferredExtension);
  }

  const exact = resolveStoredVariant(folder, coverType, requestedHeight, preferredExtension);
  if (exact) return exact;

  const largerHeights = UI_COVER_HEIGHTS
    .filter((height) => height > requestedHeight)
    .sort((left, right) => left - right);
  for (const height of largerHeights) {
    const larger = resolveStoredVariant(folder, coverType, height, preferredExtension);
    if (larger) return larger;
  }

  const origin = resolveStoredVariant(folder, coverType, null, preferredExtension);
  if (origin) return origin;

  const smallerHeights = UI_COVER_HEIGHTS
    .filter((height) => height < requestedHeight)
    .sort((left, right) => right - left);
  for (const height of smallerHeights) {
    const smaller = resolveStoredVariant(folder, coverType, height, preferredExtension);
    if (smaller) return smaller;
  }
  return null;
}

/**
 * Album/artist: prefer proxy. Video: bare cover.jpg is full-res origin; height
 * suffixes are the aspect-preserving proxies used by grids/cards.
 */
function resolveUiMediaCoverFilePath(
  folder: string,
  filename: string,
  options: { preferOrigin?: boolean } = {},
): string | null {
  if (options.preferOrigin && !requestedCoverHasProxyHeight(filename)) {
    const match = path.basename(String(filename || "")).match(/^(.+?)(\.[a-z0-9]+)$/i);
    if (match) {
      const origin = resolveStoredVariant(folder, match[1], null, match[2]);
      if (origin) return origin;
    }
  }
  return resolveUiMediaCoverProxyFilePath(folder, filename);
}

function sendMediaCover(res: any, filePath: string): void {
  // Lidarr/Jellyfin: revisioned local URLs are long-lived. `?rev=` already
  // busts when the source changes, so immutable caching is safe and fast.
  res.setHeader("Cache-Control", "public, max-age=31536000, immutable");
  res.sendFile(path.resolve(filePath), {
    acceptRanges: true,
    cacheControl: false,
    etag: true,
    lastModified: true,
  });
}

router.get("/Albums/:albumId/:filename", async (req, res) => {
  const albumId = normalizeMediaCoverEntityId(req.params.albumId);
  const albumFolder = albumId ? mediaCoverFolder("Albums", albumId) : null;
  if (!albumId || !albumFolder) {
    return res.status(400).end();
  }
  const filename = String(req.params.filename || "");
  const filePath = resolveUiMediaCoverFilePath(albumFolder, filename);

  if (!filePath) {
    return res.status(404).end();
  }
  return sendMediaCover(res, filePath);
});

router.get("/Videos/:videoId/:filename", async (req, res) => {
  const videoId = normalizeMediaCoverEntityId(req.params.videoId);
  const videoFolder = videoId ? mediaCoverFolder("Videos", videoId) : null;
  if (!videoId || !videoFolder) {
    return res.status(400).end();
  }
  const filename = String(req.params.filename || "");
  const filePath = resolveUiMediaCoverFilePath(videoFolder, filename, { preferOrigin: true });

  if (!filePath) {
    return res.status(404).end();
  }
  return sendMediaCover(res, filePath);
});

router.get("/:artistId/:filename", async (req, res) => {
  const artistId = normalizeMediaCoverEntityId(req.params.artistId);
  const artistFolder = artistId ? mediaCoverFolder(artistId) : null;
  if (!artistId || !artistFolder) {
    return res.status(400).end();
  }
  const filename = String(req.params.filename || "");
  const filePath = resolveUiMediaCoverFilePath(artistFolder, filename);

  if (!filePath) {
    return res.status(404).end();
  }
  return sendMediaCover(res, filePath);
});

export default router;
